name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
    - name: Deploy and run on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          pkill -f 'spring-boot:run' || true
          rm -rf spring-boot-app1
          git clone https://github.com/eungsu/spring-boot-app1.git
          cd spring-boot-app1
          chmod +x ./mvnw
          nohup ./mvnw spring-boot:run > app.log 2>&1 &
        EOF
