name: SSH Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Decode key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > private_key
          chmod 600 private_key

      - name: Test SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "hostname && whoami"
