# 워크 플로우 이름
name: Java CI with Gradle 


# 워크 플로우가 언제 실행 될지를 정한다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# 워크 플로우가 깃 레포에 대한 권한을 읽기 만 가능하게 설정한다.
permissions:
  contents: read


# 워크플로우에서 할 작업 정의한다.
jobs:
  deploy:
    runs-on: ubuntu-latest

    # 위의 빌드작업한 JAR 파일 = 아티팩트를 다운로드
    steps:
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
      
